email_min_score: 88
email_min_sentiment: 0.5

sites:
  - name: "BusinessWire"
    url: "https://bw-prod-sitemap.s3.us-east-1.amazonaws.com/webdmz1.vaprod.businesswire.com/home/%Y-%m-%d.xml.gz"
    type: "sitemap"
    max_urls: 250
    max_chars: 3500
    min_chars: 1000
    include_filters:
      - "/en/"
    content_selector: "#bw-release-story"
    title_selector: "h1"
    date_regex: '/(\d{8})\d+/'
    date_format: "%Y%m%d"

  - name: "StockWatch"
    url: "https://www.stockwatch.com/News/Search?hours=24&region=U"
    type: "page"
    max_urls: 250
    max_chars: 3500
    min_chars: 1000
    include_filters:
      - "/News/Item/U-"
    content_selector: "#MainContent_NewsText"
    title_selector: "h3"
    date_regex: '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}) ET'
    date_format: "%Y-%m-%d %H:%M"

  - name: "Investing.com"
    url: "https://www.investing.com/news/latest-news"
    type: "page"
    max_urls: 250
    max_chars: 3500
    min_chars: 1000
    # No content_selector needed as parser.py uses JSON extraction
    paywall_selector: ".paywall-banner, .pro-subscription-banner"
    title_selector: "h1"
    date_regex: 'Published (\d{2}/\d{2}/\d{4}, \d{2}:\d{2} [AP]M)'
    date_format: "%m/%d/%Y, %I:%M %p"
